# -*- coding: utf-8 -*-
"""CIE-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gw64sF65mfTgRb9O_4RUVfzbm6O9Ub3X
"""

import pandas as pd
data = pd.read_csv('mtcars.csv')
data

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
plt.hist(data['mpg'], bins=10, edgecolor='black',color='pink')
plt.title('Histogram of Miles Per Gallon (mpg)')
plt.xlabel('Miles Per Gallon (mpg)')
plt.ylabel('Frequency')
plt.show()

import pandas as pd
plt.figure(figsize=(10, 6))
plt.scatter(data['wt'], data['mpg'],color='red')
plt.title('Scatter Plot of Weight V/S Miles Per Gallon')
plt.xlabel('Weight (1000 lbs)')
plt.ylabel('Miles Per Gallon (mpg)')
plt.show()

transmission_counts = data['am'].value_counts()
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
transmission_counts.plot(kind='bar',color='pink',edgecolor='black')
plt.title('Frequency Distribution of Transmission Types')
plt.xlabel('Transmission (0 = Automatic, 1 = Manual)')
plt.ylabel('Frequency')
plt.xticks(rotation=0)
plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
data.boxplot(column='mpg',color='red')
plt.title('Box and Whisker Plot of Miles Per Gallon (mpg)')
plt.ylabel('Miles Per Gallon (mpg)')
plt.show()

summary = data['mpg'].describe()
print(summary[['min', '25%', '50%', '75%', 'max']])